# Generated by Django 4.2.3 on 2023-08-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='Turno',
            new_name='fecha',
        ),
    ]
